name: "Dispatch Change Event"
on:
  push:
    branches:
      - main

jobs:
  build:
    name: Deployment to Server
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Executing the CURL Command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.UAT_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.UAT_KEY_FILE }}
          script: |
            curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.REPO_DISPATCH_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/mt-technologies-ltd/lebu-pay-api/dispatches \
            -d '{"event_type":"AIRTIME_MAIN_CHANGE"}'
